#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Curve generation initialisation module.

This module runs the complete curve generation workflow independently.
It orchestrates various generators for financial curve processing.

Author: Yunfei Ma
"""

from __future__ import annotations

import datetime
import json
import os
import pathlib
import sys
import traceback

# Minimal bootstrap for direct execution: add project root so absolute
# package imports work when running `python curves\initialise.py`.
if __name__ == "__main__":
    _PROJECT_ROOT = pathlib.Path(__file__).resolve().parents[1]
    if str(_PROJECT_ROOT) not in sys.path:
        sys.path.insert(0, str(_PROJECT_ROOT))

# Clean imports - all absolute paths
from curves.utils.generator_utils import get_mtime_date
from curves.utils.retrieve import updateInstrumentDef, retrieveCNBDTS, retrieveFuturesTS
from settings.fixed_income import BondConfig
from settings.general import GeneralConfig
from settings.paths import DIR_INPUT

# Import generators dynamically to avoid dependency issues at module load time
import importlib


_PROJECT_ROOT = pathlib.Path(__file__).resolve().parents[1]
_INITIALISE_STATE_DIR = _PROJECT_ROOT / "cache" / "curve_initialise"
# Use TBond-spds.pkl as completion artifact (generated by StatGenerator in EOD)
# Previously used MNote-spds.pkl, but that's generated by pairs which is no longer in EOD pipeline
_COMPLETION_ARTIFACT = DIR_INPUT / "TBond-spds.pkl"
_REQUIRED_DAILY_INPUTS = {
    "bond_database": DIR_INPUT / "database-px.pkl",
    "futures_database": DIR_INPUT / "futures-px.pkl",
}


def _initialise_marker_path(asof: datetime.date) -> pathlib.Path:
    return _INITIALISE_STATE_DIR / f"{asof:%Y%m%d}.json"


def _daily_inputs_ready(asof: datetime.date) -> tuple[bool, list[str]]:
    pending: list[str] = []
    for label, path in _REQUIRED_DAILY_INPUTS.items():
        mtime = get_mtime_date(path)
        if mtime is None:
            pending.append(f"{label} ({path.name}: missing)")
            continue

        # Daily inputs (bond_database, futures_database) must be from today
        if mtime < asof:
            pending.append(f"{label} ({path.name}: dated {mtime.isoformat()})")
    return (len(pending) == 0, pending)


def _load_marker(asof: datetime.date) -> dict | None:
    marker_path = _initialise_marker_path(asof)
    if not marker_path.exists():
        return None
    try:
        with marker_path.open("r", encoding="utf-8") as handle:
            return json.load(handle)
    except Exception:
        return None


def _generation_completed_today(asof: datetime.date) -> bool:
    if not _completion_artifact_ready(asof):
        return False
    marker = _load_marker(asof)
    if not marker:
        return True
    return marker.get("status") == "completed"


def _completion_artifact_ready(asof: datetime.date) -> bool:
    return get_mtime_date(_COMPLETION_ARTIFACT) == asof


def _write_completion_marker(
    asof: datetime.date,
    *,
    generators: list[str],
    pairs_generated: bool,
) -> None:
    _INITIALISE_STATE_DIR.mkdir(parents=True, exist_ok=True)
    marker = {
        "date": asof.isoformat(),
        "status": "completed",
        "completed_at": datetime.datetime.now().isoformat(timespec="seconds"),
        "generators": generators,
        "pairs_generated": pairs_generated,
        "completion_artifact": str(_COMPLETION_ARTIFACT),
        "required_inputs": {
            label: str(path) for label, path in _REQUIRED_DAILY_INPUTS.items()
        },
    }
    marker_path = _initialise_marker_path(asof)
    with marker_path.open("w", encoding="utf-8") as handle:
        json.dump(marker, handle, indent=2)


def run_data_updates(asof: datetime.date | None = None) -> None:
    """Check and warn about missing/outdated data files (non-blocking).

    Does NOT attempt to fetch data — that only happens via explicit --update-data.
    When running for a past date, data is considered valid if it exists (even if
    dated after asof). Only warns when running for today if data is outdated.
    """
    t = datetime.datetime.today()
    today = t.date()

    # Only warn about stale data if running for today
    if asof and asof < today:
        # Running for a past date — data files may be more recent, that's fine
        return

    # Running for today — check if data is outdated
    missing_files = []
    for label, fpath in [
        ("instrument definitions", DIR_INPUT / "futures-InstrumentInfo.pkl"),
        ("bond database", DIR_INPUT / "database-px.pkl"),
        ("futures database", DIR_INPUT / "futures-px.pkl"),
    ]:
        mtime = get_mtime_date(fpath)
        if mtime is None:
            missing_files.append(f"{label} (missing)")

    if missing_files:
        print(f"INFO: Missing data files (run with --update-data to retrieve):")
        for item in missing_files:
            print(f"      - {item}")

def main(asof: datetime.date | None = None) -> str:
    """Main curve generation workflow (INFO/WARNING only).

    Args:
        asof: Date for calibration (defaults to today if not specified)
    """
    print("INFO: Starting curve generation...")
    print(f"INFO: curves package path: {pathlib.Path(__file__).resolve().parent}")
    GeneralConfig.N_CORE = 1
    if asof is None:
        asof = datetime.datetime.today().date()
    
    force = True #os.environ.get("FI_FORCE_RERUN", "0").strip().lower() in {"1", "true", "yes"}
    try:
        if not force and _generation_completed_today(asof):
            print(
                f"INFO: Curve generation already completed for {asof.isoformat()} "
                f"({_COMPLETION_ARTIFACT.name} updated today) — skipping rerun. "
                f"Set FI_FORCE_RERUN=1 to override."
            )
            return "Skipped: MNote-spds.pkl already updated today"

        # Step 1: Check for missing data files
        run_data_updates(asof=asof)

        ready, pending_inputs = _daily_inputs_ready(asof)
        if not ready:
            print("INFO: Skipping curve generation until today's prerequisite files are ready:")
            for item in pending_inputs:
                print(f"INFO:   - {item}")
            return "Skipped: prerequisite inputs not ready"

        # Step 2: Run generators in order
        generators = [
            ("TrendGenerator",            "trend"),
            ("BondCurveGenerator",        "rates"),
            ("CreditSpreadGenerator",     "credit"),
            ("IRSGenerator",              "irs"),
            # Analytics layer must run before StatGenerator so compute_futures_stats()
            # can read futures-analytics.pkl (Wind IRR/FYTM/closes) for the
            # Bond-Futures / Term Basis / Futures-Swap spreads.
            ("FuturesAnalyticsGenerator", "futures_analytics"),
            ("StatGenerator",             "stat"),
        ]
        
        success_count = 0
        completed_generators: list[str] = []
        asof_str = asof.strftime('%Y%m%d')  # Convert to YYYYMMDD format for generators

        for generator_name, module_name in generators:
            try:
                print(f"INFO: Running {generator_name} for {asof_str}...")

                # Import generator dynamically to avoid dependency issues
                spec = importlib.import_module(f"curves.generators.{module_name}")
                generator_class = getattr(spec, generator_name)

                if generator_name == "BondCurveGenerator":
                    for bond_type in ['TBond', 'CBond']:
                        print(f"INFO: Generating {bond_type} curve...")
                        generator_class.main(bond_type=bond_type, date=asof_str)
                elif generator_name == "CreditSpreadGenerator":
                    for bond_type in BondConfig.INCLUDE_FILTERS.keys():
                        print(f"INFO: Generating {bond_type} curve...")
                        generator_class.main(bond_type=bond_type, date=asof_str)
                else:
                    # TrendGenerator, IRSGenerator, StatGenerator all accept date
                    generator_class.main(date=asof_str)

                print(f"INFO: {generator_name} completed successfully")
                success_count += 1
                completed_generators.append(generator_name)

            except ImportError as e:
                print(f"WARNING: Could not import {generator_name}: {e}")
            except Exception as e:
                print(f"ERROR: Error running {generator_name}: {e}")
                
        print(f"INFO: Summary: {success_count}/{len(generators)} generators completed successfully")

        # EOD completion — pairs runs on-demand only, not in EOD pipeline
        if success_count == len(generators) and _completion_artifact_ready(asof):
            _write_completion_marker(
                asof,
                generators=completed_generators,
                pairs_generated=False,
            )
            print("INFO: All curve generation tasks completed!")
            return "Completed curve generation"
        elif success_count == len(generators):
            print(
                f"WARNING: {_COMPLETION_ARTIFACT.name} was not updated for {asof.isoformat()} "
                "(run pairs analysis separately if needed)"
            )
            return "Warning: completion artifact not updated"
        else:
            print("WARNING: Some generators failed - check logs above for details")
            return "Warning: some generators failed"
              
    except Exception as e:
        print(f"CRITICAL: Fatal error: {e}")
        traceback.print_exc()
        sys.exit(1)
#%%
if __name__ == "__main__":
    main()
  